// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kafka.proto

package org.example;

public final class Kafka {
  private Kafka() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code org.example.ClientType}
   */
  public enum ClientType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>TARGET = 0;</code>
     */
    TARGET(0),
    /**
     * <code>SENSOR1 = 1;</code>
     */
    SENSOR1(1),
    /**
     * <code>SENSOR2 = 2;</code>
     */
    SENSOR2(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>TARGET = 0;</code>
     */
    public static final int TARGET_VALUE = 0;
    /**
     * <code>SENSOR1 = 1;</code>
     */
    public static final int SENSOR1_VALUE = 1;
    /**
     * <code>SENSOR2 = 2;</code>
     */
    public static final int SENSOR2_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ClientType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ClientType forNumber(int value) {
      switch (value) {
        case 0: return TARGET;
        case 1: return SENSOR1;
        case 2: return SENSOR2;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ClientType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ClientType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ClientType>() {
            public ClientType findValueByNumber(int number) {
              return ClientType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.example.Kafka.getDescriptor().getEnumTypes().get(0);
    }

    private static final ClientType[] VALUES = values();

    public static ClientType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ClientType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:org.example.ClientType)
  }

  public interface KafkaMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.example.KafkaMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.org.example.ClientType clientType = 1;</code>
     * @return The enum numeric value on the wire for clientType.
     */
    int getClientTypeValue();
    /**
     * <code>.org.example.ClientType clientType = 1;</code>
     * @return The clientType.
     */
    org.example.Kafka.ClientType getClientType();

    /**
     * <code>.org.example.Coordinate coordinate = 2;</code>
     * @return Whether the coordinate field is set.
     */
    boolean hasCoordinate();
    /**
     * <code>.org.example.Coordinate coordinate = 2;</code>
     * @return The coordinate.
     */
    org.example.Kafka.Coordinate getCoordinate();
    /**
     * <code>.org.example.Coordinate coordinate = 2;</code>
     */
    org.example.Kafka.CoordinateOrBuilder getCoordinateOrBuilder();
  }
  /**
   * Protobuf type {@code org.example.KafkaMessage}
   */
  public static final class KafkaMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.example.KafkaMessage)
      KafkaMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use KafkaMessage.newBuilder() to construct.
    private KafkaMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private KafkaMessage() {
      clientType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new KafkaMessage();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.Kafka.internal_static_org_example_KafkaMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.Kafka.internal_static_org_example_KafkaMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.Kafka.KafkaMessage.class, org.example.Kafka.KafkaMessage.Builder.class);
    }

    public static final int CLIENTTYPE_FIELD_NUMBER = 1;
    private int clientType_ = 0;
    /**
     * <code>.org.example.ClientType clientType = 1;</code>
     * @return The enum numeric value on the wire for clientType.
     */
    @java.lang.Override public int getClientTypeValue() {
      return clientType_;
    }
    /**
     * <code>.org.example.ClientType clientType = 1;</code>
     * @return The clientType.
     */
    @java.lang.Override public org.example.Kafka.ClientType getClientType() {
      org.example.Kafka.ClientType result = org.example.Kafka.ClientType.forNumber(clientType_);
      return result == null ? org.example.Kafka.ClientType.UNRECOGNIZED : result;
    }

    public static final int COORDINATE_FIELD_NUMBER = 2;
    private org.example.Kafka.Coordinate coordinate_;
    /**
     * <code>.org.example.Coordinate coordinate = 2;</code>
     * @return Whether the coordinate field is set.
     */
    @java.lang.Override
    public boolean hasCoordinate() {
      return coordinate_ != null;
    }
    /**
     * <code>.org.example.Coordinate coordinate = 2;</code>
     * @return The coordinate.
     */
    @java.lang.Override
    public org.example.Kafka.Coordinate getCoordinate() {
      return coordinate_ == null ? org.example.Kafka.Coordinate.getDefaultInstance() : coordinate_;
    }
    /**
     * <code>.org.example.Coordinate coordinate = 2;</code>
     */
    @java.lang.Override
    public org.example.Kafka.CoordinateOrBuilder getCoordinateOrBuilder() {
      return coordinate_ == null ? org.example.Kafka.Coordinate.getDefaultInstance() : coordinate_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (clientType_ != org.example.Kafka.ClientType.TARGET.getNumber()) {
        output.writeEnum(1, clientType_);
      }
      if (coordinate_ != null) {
        output.writeMessage(2, getCoordinate());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (clientType_ != org.example.Kafka.ClientType.TARGET.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, clientType_);
      }
      if (coordinate_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getCoordinate());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.example.Kafka.KafkaMessage)) {
        return super.equals(obj);
      }
      org.example.Kafka.KafkaMessage other = (org.example.Kafka.KafkaMessage) obj;

      if (clientType_ != other.clientType_) return false;
      if (hasCoordinate() != other.hasCoordinate()) return false;
      if (hasCoordinate()) {
        if (!getCoordinate()
            .equals(other.getCoordinate())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CLIENTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + clientType_;
      if (hasCoordinate()) {
        hash = (37 * hash) + COORDINATE_FIELD_NUMBER;
        hash = (53 * hash) + getCoordinate().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.example.Kafka.KafkaMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.Kafka.KafkaMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.Kafka.KafkaMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.Kafka.KafkaMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.Kafka.KafkaMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.Kafka.KafkaMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.Kafka.KafkaMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.Kafka.KafkaMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.example.Kafka.KafkaMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.example.Kafka.KafkaMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.Kafka.KafkaMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.Kafka.KafkaMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.example.Kafka.KafkaMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.example.KafkaMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.example.KafkaMessage)
        org.example.Kafka.KafkaMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.example.Kafka.internal_static_org_example_KafkaMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.example.Kafka.internal_static_org_example_KafkaMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.example.Kafka.KafkaMessage.class, org.example.Kafka.KafkaMessage.Builder.class);
      }

      // Construct using org.example.Kafka.KafkaMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        clientType_ = 0;
        coordinate_ = null;
        if (coordinateBuilder_ != null) {
          coordinateBuilder_.dispose();
          coordinateBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.example.Kafka.internal_static_org_example_KafkaMessage_descriptor;
      }

      @java.lang.Override
      public org.example.Kafka.KafkaMessage getDefaultInstanceForType() {
        return org.example.Kafka.KafkaMessage.getDefaultInstance();
      }

      @java.lang.Override
      public org.example.Kafka.KafkaMessage build() {
        org.example.Kafka.KafkaMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.example.Kafka.KafkaMessage buildPartial() {
        org.example.Kafka.KafkaMessage result = new org.example.Kafka.KafkaMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.example.Kafka.KafkaMessage result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.clientType_ = clientType_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.coordinate_ = coordinateBuilder_ == null
              ? coordinate_
              : coordinateBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.example.Kafka.KafkaMessage) {
          return mergeFrom((org.example.Kafka.KafkaMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.example.Kafka.KafkaMessage other) {
        if (other == org.example.Kafka.KafkaMessage.getDefaultInstance()) return this;
        if (other.clientType_ != 0) {
          setClientTypeValue(other.getClientTypeValue());
        }
        if (other.hasCoordinate()) {
          mergeCoordinate(other.getCoordinate());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                clientType_ = input.readEnum();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                input.readMessage(
                    getCoordinateFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int clientType_ = 0;
      /**
       * <code>.org.example.ClientType clientType = 1;</code>
       * @return The enum numeric value on the wire for clientType.
       */
      @java.lang.Override public int getClientTypeValue() {
        return clientType_;
      }
      /**
       * <code>.org.example.ClientType clientType = 1;</code>
       * @param value The enum numeric value on the wire for clientType to set.
       * @return This builder for chaining.
       */
      public Builder setClientTypeValue(int value) {
        clientType_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.org.example.ClientType clientType = 1;</code>
       * @return The clientType.
       */
      @java.lang.Override
      public org.example.Kafka.ClientType getClientType() {
        org.example.Kafka.ClientType result = org.example.Kafka.ClientType.forNumber(clientType_);
        return result == null ? org.example.Kafka.ClientType.UNRECOGNIZED : result;
      }
      /**
       * <code>.org.example.ClientType clientType = 1;</code>
       * @param value The clientType to set.
       * @return This builder for chaining.
       */
      public Builder setClientType(org.example.Kafka.ClientType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        clientType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.org.example.ClientType clientType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        clientType_ = 0;
        onChanged();
        return this;
      }

      private org.example.Kafka.Coordinate coordinate_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.example.Kafka.Coordinate, org.example.Kafka.Coordinate.Builder, org.example.Kafka.CoordinateOrBuilder> coordinateBuilder_;
      /**
       * <code>.org.example.Coordinate coordinate = 2;</code>
       * @return Whether the coordinate field is set.
       */
      public boolean hasCoordinate() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.org.example.Coordinate coordinate = 2;</code>
       * @return The coordinate.
       */
      public org.example.Kafka.Coordinate getCoordinate() {
        if (coordinateBuilder_ == null) {
          return coordinate_ == null ? org.example.Kafka.Coordinate.getDefaultInstance() : coordinate_;
        } else {
          return coordinateBuilder_.getMessage();
        }
      }
      /**
       * <code>.org.example.Coordinate coordinate = 2;</code>
       */
      public Builder setCoordinate(org.example.Kafka.Coordinate value) {
        if (coordinateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          coordinate_ = value;
        } else {
          coordinateBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.org.example.Coordinate coordinate = 2;</code>
       */
      public Builder setCoordinate(
          org.example.Kafka.Coordinate.Builder builderForValue) {
        if (coordinateBuilder_ == null) {
          coordinate_ = builderForValue.build();
        } else {
          coordinateBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.org.example.Coordinate coordinate = 2;</code>
       */
      public Builder mergeCoordinate(org.example.Kafka.Coordinate value) {
        if (coordinateBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            coordinate_ != null &&
            coordinate_ != org.example.Kafka.Coordinate.getDefaultInstance()) {
            getCoordinateBuilder().mergeFrom(value);
          } else {
            coordinate_ = value;
          }
        } else {
          coordinateBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.org.example.Coordinate coordinate = 2;</code>
       */
      public Builder clearCoordinate() {
        bitField0_ = (bitField0_ & ~0x00000002);
        coordinate_ = null;
        if (coordinateBuilder_ != null) {
          coordinateBuilder_.dispose();
          coordinateBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.org.example.Coordinate coordinate = 2;</code>
       */
      public org.example.Kafka.Coordinate.Builder getCoordinateBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getCoordinateFieldBuilder().getBuilder();
      }
      /**
       * <code>.org.example.Coordinate coordinate = 2;</code>
       */
      public org.example.Kafka.CoordinateOrBuilder getCoordinateOrBuilder() {
        if (coordinateBuilder_ != null) {
          return coordinateBuilder_.getMessageOrBuilder();
        } else {
          return coordinate_ == null ?
              org.example.Kafka.Coordinate.getDefaultInstance() : coordinate_;
        }
      }
      /**
       * <code>.org.example.Coordinate coordinate = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.example.Kafka.Coordinate, org.example.Kafka.Coordinate.Builder, org.example.Kafka.CoordinateOrBuilder> 
          getCoordinateFieldBuilder() {
        if (coordinateBuilder_ == null) {
          coordinateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.example.Kafka.Coordinate, org.example.Kafka.Coordinate.Builder, org.example.Kafka.CoordinateOrBuilder>(
                  getCoordinate(),
                  getParentForChildren(),
                  isClean());
          coordinate_ = null;
        }
        return coordinateBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.example.KafkaMessage)
    }

    // @@protoc_insertion_point(class_scope:org.example.KafkaMessage)
    private static final org.example.Kafka.KafkaMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.example.Kafka.KafkaMessage();
    }

    public static org.example.Kafka.KafkaMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<KafkaMessage>
        PARSER = new com.google.protobuf.AbstractParser<KafkaMessage>() {
      @java.lang.Override
      public KafkaMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<KafkaMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<KafkaMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.example.Kafka.KafkaMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CoordinateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.example.Coordinate)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 x = 1;</code>
     * @return The x.
     */
    int getX();

    /**
     * <code>int32 y = 2;</code>
     * @return The y.
     */
    int getY();
  }
  /**
   * Protobuf type {@code org.example.Coordinate}
   */
  public static final class Coordinate extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.example.Coordinate)
      CoordinateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Coordinate.newBuilder() to construct.
    private Coordinate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Coordinate() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Coordinate();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.Kafka.internal_static_org_example_Coordinate_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.Kafka.internal_static_org_example_Coordinate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.Kafka.Coordinate.class, org.example.Kafka.Coordinate.Builder.class);
    }

    public static final int X_FIELD_NUMBER = 1;
    private int x_ = 0;
    /**
     * <code>int32 x = 1;</code>
     * @return The x.
     */
    @java.lang.Override
    public int getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private int y_ = 0;
    /**
     * <code>int32 y = 2;</code>
     * @return The y.
     */
    @java.lang.Override
    public int getY() {
      return y_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (x_ != 0) {
        output.writeInt32(1, x_);
      }
      if (y_ != 0) {
        output.writeInt32(2, y_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (x_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, x_);
      }
      if (y_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, y_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.example.Kafka.Coordinate)) {
        return super.equals(obj);
      }
      org.example.Kafka.Coordinate other = (org.example.Kafka.Coordinate) obj;

      if (getX()
          != other.getX()) return false;
      if (getY()
          != other.getY()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + getX();
      hash = (37 * hash) + Y_FIELD_NUMBER;
      hash = (53 * hash) + getY();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.example.Kafka.Coordinate parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.Kafka.Coordinate parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.Kafka.Coordinate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.Kafka.Coordinate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.Kafka.Coordinate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.Kafka.Coordinate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.Kafka.Coordinate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.Kafka.Coordinate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.example.Kafka.Coordinate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.example.Kafka.Coordinate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.Kafka.Coordinate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.Kafka.Coordinate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.example.Kafka.Coordinate prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.example.Coordinate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.example.Coordinate)
        org.example.Kafka.CoordinateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.example.Kafka.internal_static_org_example_Coordinate_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.example.Kafka.internal_static_org_example_Coordinate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.example.Kafka.Coordinate.class, org.example.Kafka.Coordinate.Builder.class);
      }

      // Construct using org.example.Kafka.Coordinate.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        x_ = 0;
        y_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.example.Kafka.internal_static_org_example_Coordinate_descriptor;
      }

      @java.lang.Override
      public org.example.Kafka.Coordinate getDefaultInstanceForType() {
        return org.example.Kafka.Coordinate.getDefaultInstance();
      }

      @java.lang.Override
      public org.example.Kafka.Coordinate build() {
        org.example.Kafka.Coordinate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.example.Kafka.Coordinate buildPartial() {
        org.example.Kafka.Coordinate result = new org.example.Kafka.Coordinate(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.example.Kafka.Coordinate result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.x_ = x_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.y_ = y_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.example.Kafka.Coordinate) {
          return mergeFrom((org.example.Kafka.Coordinate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.example.Kafka.Coordinate other) {
        if (other == org.example.Kafka.Coordinate.getDefaultInstance()) return this;
        if (other.getX() != 0) {
          setX(other.getX());
        }
        if (other.getY() != 0) {
          setY(other.getY());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                x_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                y_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int x_ ;
      /**
       * <code>int32 x = 1;</code>
       * @return The x.
       */
      @java.lang.Override
      public int getX() {
        return x_;
      }
      /**
       * <code>int32 x = 1;</code>
       * @param value The x to set.
       * @return This builder for chaining.
       */
      public Builder setX(int value) {

        x_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 x = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0;
        onChanged();
        return this;
      }

      private int y_ ;
      /**
       * <code>int32 y = 2;</code>
       * @return The y.
       */
      @java.lang.Override
      public int getY() {
        return y_;
      }
      /**
       * <code>int32 y = 2;</code>
       * @param value The y to set.
       * @return This builder for chaining.
       */
      public Builder setY(int value) {

        y_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 y = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.example.Coordinate)
    }

    // @@protoc_insertion_point(class_scope:org.example.Coordinate)
    private static final org.example.Kafka.Coordinate DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.example.Kafka.Coordinate();
    }

    public static org.example.Kafka.Coordinate getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Coordinate>
        PARSER = new com.google.protobuf.AbstractParser<Coordinate>() {
      @java.lang.Override
      public Coordinate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Coordinate> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Coordinate> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.example.Kafka.Coordinate getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_KafkaMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_KafkaMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_Coordinate_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_Coordinate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013kafka.proto\022\013org.example\"h\n\014KafkaMessa" +
      "ge\022+\n\nclientType\030\001 \001(\0162\027.org.example.Cli" +
      "entType\022+\n\ncoordinate\030\002 \001(\0132\027.org.exampl" +
      "e.Coordinate\"\"\n\nCoordinate\022\t\n\001x\030\001 \001(\005\022\t\n" +
      "\001y\030\002 \001(\005*2\n\nClientType\022\n\n\006TARGET\020\000\022\013\n\007SE" +
      "NSOR1\020\001\022\013\n\007SENSOR2\020\002b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_example_KafkaMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_example_KafkaMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_KafkaMessage_descriptor,
        new java.lang.String[] { "ClientType", "Coordinate", });
    internal_static_org_example_Coordinate_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_example_Coordinate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_Coordinate_descriptor,
        new java.lang.String[] { "X", "Y", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
